POST http://localhost:8080/book
Content-Type: application/x-www-form-urlencoded;charset=utf-8

title=zażółć gęślą jaźń&description=jakiś opis&rating=3&publisherName=Helion&authorId=1&authorId=2
###

GET http://localhost:8080/book/1
###

GET http://localhost:8080/books
###

GET http://localhost:8080/books?rating=2

### publisher is not null
GET http://localhost:8080/books/publisher

### publisher with given id
GET http://localhost:8080/books/publisher?id=10

### author with given id
GET http://localhost:8080/books/author?id=2

###
PUT http://localhost:8080/book/1?title=zażółć gęślą jaźń123&description=jakiś opis123&rating=3

###
DELETE http://localhost:8080/book/1